package com.jaison.bompod.model.realm;

import org.apache.kafka.connect.data.Decimal;
import org.apache.kafka.connect.data.Schema;

import java.math.BigDecimal;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class quotation_pos extends RealmObject {

    @PrimaryKey
    private int id;
    private int pos_id;
    private int product_id;
    private Quotation quotation;
    private String gm_id;
    private String comments;
    private String created;


   /* class  Quotation extends  RealmObject
    {
        int scale;
        byte [] value;
    }
*/

    // Standard getters & setters generated by your IDE…
    public int getid() {
        return id;
    }

    public void setid(int id) {
        this.id = id;
    }

    public int getproduct_id() {
        return product_id;
    }

    public void setproduct_id(int product_id) {
        this.product_id = product_id;
    }

    public int getpos_id() {
        return pos_id;
    }

    public void setpos_id(int pos_id) {
        this.pos_id = pos_id;
    }
    public float getquotation() {
        Schema schema = Decimal.schema(quotation.scale);
        BigDecimal decimal = Decimal.toLogical(schema, quotation.value.getBytes());
        return decimal.floatValue();
    }
    public String getgm_id() {
        return gm_id;
    }
    public void setgm_id(String gm_id) {
        this.gm_id = gm_id;
    }
    public String getcreated() {
        return created;
    }
    public void setcreated(String created) {
        this.created = created;
    }

    public String getcomments() {
        return comments;
    }
    public void setcomments(String comments) {
        this.comments = comments;
    }
}



